export const LISTS_ITEMS_REORDER_IN_LIST = "LISTS_ITEMS_REORDER_IN_LIST";
export const LISTS_ITEMS_MOVE_TO_LIST = "LISTS_ITEMS_MOVE_TO_LIST";
export const LISTS_ITEMS_SET_FILTER = "LISTS_ITEMS_SET_FILTER";
export const LISTS_ITEMS_ADD_ITEM = "LISTS_ITEMS_ADD_ITEM";
export const LISTS_ITEMS_TOGGLE_EDIT = "LISTS_ITEMS_TOGGLE_EDIT";
export const LISTS_ITEMS_SAVE = "LISTS_ITEMS_SAVE";
export const LISTS_ITEMS_DELETE = "LISTS_ITEMS_DELETE";
